import ThemeRegistry from '@/theme/themeRegistry';
import './globals.css';
import type { Metadata } from 'next';
import Layout from '@/components/Layout';

export const metadata: Metadata = {
  title: 'Dash UI - admin template',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry options={{ key: 'mui' }}>
          <Layout>{children}</Layout>
        </ThemeRegistry>
      </body>
    </html>
  );
}
